/**
 * PR Template for secret remediation
 */

export interface PRTemplateData {
  repoOwner: string;
  repoName: string;
  branch: string;
  secrets: Array<{
    type: string;
    file: string;
    line: number;
    masked: string;
    severity: string;
  }>;
  commitSha: string;
  commitUrl: string;
}

export function generatePRTitle(count: number): string {
  return count === 1
    ? '🔒 Security: Remove detected secret'
    : `🔒 Security: Remove ${count} detected secrets`;
}

export function generatePRBody(data: PRTemplateData): string {
  const severityEmoji: Record<string, string> = {
    high: '🚨',
    medium: '⚠️',
    low: '📝',
  };

  let body = `# 🔒 Detected Secrets - Immediate Action Required

**KeySpinner** has detected **${data.secrets.length} potential ${data.secrets.length === 1 ? 'secret' : 'secrets'}** in your repository.

## ⚡ Why This Matters

Exposed credentials are a leading cause of security breaches. Attackers actively scan GitHub for leaked API keys, tokens, and passwords. Once exposed, you must:

1. **Revoke/rotate the compromised credential** immediately
2. **Remove it from this repository** (use this PR)
3. **Consider it compromised** - don't reuse the same value

## 📋 Detected Secrets

| Type | File | Line | Severity |
|------|------|------|----------|
`;

  for (const secret of data.secrets) {
    const emoji = severityEmoji[secret.severity] ?? '❓';
    body += `| ${secret.type} | \`${secret.file}\` | ${secret.line} | ${emoji} ${secret.severity.toUpperCase()} |\n`;
  }

  body += `
## 🔧 Required Actions

### 1. Rotate All Affected Credentials

These secrets are now compromised. You must rotate them:

`;

  // Group by type for actionable advice
  const byType = new Map<string, typeof data.secrets>();
  for (const s of data.secrets) {
    if (!byType.has(s.type)) byType.set(s.type, []);
    byType.get(s.type)!.push(s);
  }

  for (const [type, secrets] of byType) {
    body += `**${type}** (${secrets.length} found)\n`;
    body += getRotationInstructions(type);
    body += '\n';
  }

  body += `
### 2. Review and Merge This PR

This PR removes the exposed secrets from your codebase. After rotating credentials:
1. Review the changes
2. Ensure no functionality breaks (you may need to update environment variables)
3. Merge this PR

### 3. Prevent Future Leaks

Consider these best practices:
- Use environment variables for secrets (never commit them)
- Add \`.env\` to \`.gitignore\`
- Enable branch protection rules requiring PR reviews
- Use pre-commit hooks like \`gitleaks\` or \`truffleHog\`
- **Scan regularly with KeySpinner CLI**: \`npx keyspinner-scan\`

## 📊 Scan Details

- **Commit**: \`${data.commitSha}\`
- **Branch**: \`${data.branch}\`
- **Scan Time**: ${new Date().toISOString()}

---

Generated by [KeySpinner CLI](https://github.com/eylulsenakumral/keyspinner) - Security scanning for GitHub repositories
`;

  return body;
}

function getRotationInstructions(type: string): string {
  const instructions: Record<string, string> = {
    'GitHub Personal Access Token': `- Go to GitHub → Settings → Developer settings → Personal access tokens
- Revoke the exposed token
- Create a new token with required scopes
- Update your applications to use the new token`,

    'GitHub OAuth Access Token': `- OAuth tokens cannot be rotated - the user must re-authorize
- If this is a server-to-server token, regenerate in GitHub App settings
- Update applications with the new token`,

    'AWS Access Key ID': `- Go to AWS IAM → Users → Security credentials
- Find the exposed key and make it inactive
- Create a new access key
- Update applications and verify functionality
- Delete the old key`,

    'AWS Secret Access Key': `- See AWS Access Key ID above
- Never rotate access keys individually - always rotate the pair`,

    'Stripe API Key': `- **Live keys**: Go to Stripe Dashboard → API keys → Rollback key
- **Test keys**: Regenerate in test mode dashboard
- Update your webhook endpoints and applications`,

    'Stripe Test Key': `- Test keys are less critical but should still be rotated
- Regenerate in Stripe Dashboard → API keys`,

    'Slack Token': `- Go to Slack App settings → Basic Information → App Credentials
- Revoke the exposed token
- Generate a new token
- Update your bot or application`,

    'Docker Hub Token': `- Go to Docker Hub → Account Settings → Security
- Revoke the exposed access token
- Create a new token with appropriate permissions
- Update CI/CD pipelines`,

    'NPM Access Token': `- Go to npmjs.com → Access Tokens
- Revoke the exposed token
- Create a new token
- Update your .npmrc or CI configuration`,

    'Google API Key': `- Go to Google Cloud Console → APIs & Services → Credentials
- Find the API key and restrict it (or delete if not needed)
- Create a new key with proper restrictions
- Update your application`,

    'Heroku API Key': `- Go to Account Settings → API Key
- Revoke the exposed key
- Generate a new API Key
- Update your applications`,

    default: `- Refer to the service provider's documentation on credential rotation
- Revoke the exposed secret
- Generate a new secret
- Update your applications`,
  };

  return instructions[type] ?? instructions.default!;
}
